### ISSUE TITLE
finetuningする際に実行されるコード

### ISSUE THREAD

**Issue by unmo** [tosiyuki/LLaVA-JP#11]
lora finetuningする際に以下のスクリプトを用いようとしています。
https://github.com/tosiyuki/LLaVA-JP/blob/main/scripts/finetune/finetune_lora_llm_jp.sh

そこで読み込まれているpythonスクリプトのtrain_llava.pyはどこに存在していますか？

**Comment by tosiyuki** [comment]
train_llava.pyは以下にあります。
https://github.com/tosiyuki/LLaVA-JP/blob/main/train_llava.py

**Comment by unmo** [comment]
すみません。見落としていました。
クローズします。
